---
require-stack-version: ">= 2.13.1"
concurrent-tests: false
system-ghc: true
install-ghc: false
resolver: nightly-2024-05-20
compiler: ghc-9.8.2

ghc-options:
  "$locals":
    -fwrite-ide-info
    -hiedir=.hie
    -fhide-source-paths
    -fignore-optim-changes
    -Weverything
    -Wno-missing-exported-signatures
    -Wno-missed-specialisations
    -Wno-all-missed-specialisations
    -Wno-unsafe
    -Wno-safe
    -Wno-missing-local-signatures
    -Wno-monomorphism-restriction
    -Wno-missing-kind-signatures
    -Wno-missing-import-lists
    -Wno-missing-export-lists
    -Wno-incomplete-uni-patterns
    -Wno-partial-fields
    -Wno-implicit-prelude
    -Wno-deriving-typeable
    -Wno-missing-safe-haskell-mode
    -Wno-missing-role-annotations
    -Wno-term-variable-capture
    -Wno-missing-poly-kind-signatures

packages:
  - cards-discover
  - arkham-core
  - arkham-api
  - validate

allow-newer: true

extra-deps:
- github: halogenandtoast/monad-validate
  commit: e5f36d4a82875c09c6000fed8f8ced50e21b75ce
