service: arkham-horror
image: halogenandtoast/arkham-horror

servers:
  web:
    hosts:
      - 159.89.182.110

builder:
  arch:
    - arm64
    - amd64
  cache:
    type: registry

registry:
  username: halogenandtoast
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    NODE_ENV: production 
    PORT: 3000
    ASSET_HOST: https://assets.arkhamhorror.app
  secret:
    - DATABASE_URL
    - MAILTRAP_API_TOKEN
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY

proxy:
  app_port: 3000
  healthcheck:
    path: /health
