service: arkham-horror
image: halogenandtoast/arkham-horror

servers:
  web:
    hosts:
      - 159.89.182.110

builder:
  cache:
    type: registry

registry:
  username: halogenandtoast
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - NODE_ENV
    - DATABASE_URL
    - ASSET_HOST
    - PORT

# Configure a custom healthcheck (default is /up on port 3000)
healthcheck:
  path: /health
